url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "JAEYOON SIM" # the name of your site, e.g. ACME Corp.
description: ""

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-7N4TL7QCFT"
    anonymize_ip         : # true, false (default)