menu:
- {name: 'ABOUT ME', url: '/cv'}
- {name: 'EXPERIENCES', url: '/experiences'}
#- {name: 'PUBLICATIONS', url: '/publications'}
- {name: 'COURSES', url: '/courses'}
- {name: 'CONTACT', url: '/contact'}

undergraduate_courses:
- {number: 'MATH103', name: 'Calculus'}
- {number: 'MATH203', name: 'Linear Algebra'}
- {number: 'CSED101', name: 'Programming and Problem Solving'}
- {number: 'CSED211', name: 'Introduction to Computer SW Systems'}
- {number: 'CSED232', name: 'Object-Oriented Programming'}
- {number: 'CSED233', name: 'Data Structure'}
- {number: 'CSED261', name: 'Computational Mathematics'}
- {number: 'CSED273', name: 'Digital System Design'}
- {number: 'CSED291', name: 'Self-Development for Computer Science Majors'}
- {number: 'CSED321', name: 'Programming Language'}
- {number: 'CSED331', name: 'Algorithms'}
- {number: 'CSED490B', name: 'Introduction to Machine Learning'}
- {number: 'SBUCSE303', name: 'Introduction to Theory of Computation'}
- {number: 'IMEN261', name: 'Optimization Introduction'}
- {number: 'IMEN400C', name: 'Future Technology and Innovation: Cities and Future Life'}
- {number: 'CITE101', name: 'Personal Growth Statement(PGS) Design'}
- {number: 'CITE102', name: 'Introduction to Humanities and Technology Convergence'}
- {number: 'CITE201', name: 'Creative IT Design I'}
- {number: 'CITE202', name: 'Creative IT Design II'}
- {number: 'CITE203', name: 'Interaction Design Studio'}
- {number: 'CITE301', name: 'Creative IT Design III'}
- {number: 'CITE302', name: 'Creative IT Design IV'}
- {number: 'CITE306', name: 'Life Sensibility and Transhuman Studio'}
- {number: 'CITE490H', name: 'Sports Convergence Leadership Research'}
- {number: 'SBUGEO101', name: 'Environmental Geology'}
- {number: 'SBUANP101', name: 'Human Biology'}
- {number: 'SBUPHY134', name: 'Introduction to Psychology'}
- {number: 'SBUIAP390', name: 'Rethinking America'}
- {number: 'UCPHYCH7', name: 'The Person in Big Data'}
- {number: 'SNU041.0102', name: 'Reading Modern Korean Poems'}
- {number: 'KUDD122081', name: 'Basic Acting I'}
- {number: 'HASS201', name: 'World of Humanities and Arts'}
- {number: 'HASS202', name: 'Integration of Science and Society'}
- {number: 'GEDU101', name: 'Writing'}
- {number: 'GEDU117', name: 'English IV'}
- {number: 'GEDU121', name: 'Intermediate English Listening and Speaking'}
- {number: 'GEDU136', name: 'Advanced English Reading'}
- {number: 'GEDU137', name: 'Advanced English Listening and Speaking'}
- {number: 'GEDU164', name: 'Ping-pong'}
- {number: 'GEDU151', name: 'Physical Fitness'}
- {number: 'ARTS316', name: 'Understanding of the Film'}
- {number: 'HUMN413', name: 'Literature and Popular Culture'}
- {number: 'CHEM102', name: 'Chemistry(H)'}
- {number: 'CHEM106', name: 'Chemistry Experiment'}
- {number: 'LIFE103', name: 'Biology'}
- {number: 'PHYS101', name: 'Physics I'}
- {number: 'PHYS103', name: 'Physics Experiment I'}
- {number: 'PHYS104', name: 'Physics Experiment II'}
- {number: 'PHYS106', name: 'Physics II'}

graduate_courses:
- {number: 'CSED515/AIGS515', name: 'Machine Learning', url: 'machine-learning'}
- {number: 'CSED526/AIGS526', name: 'Data Mining', url: 'data-mining'}
#- {number: 'CSED537/AIGS537', name: 'Artificial Intelligence & Data Science(L)', url: 'artificial-intelligence-and-data-science'}
- {number: 'CSED538/AIGS538', name: 'Deep Learning', url: 'deep-learning'}
- {number: 'CSED539/AIGS539', name: 'Computer Vision', url: 'computer-vision'}
- {number: 'CSED551/AIGS551', name: 'Computational Photography', url: 'computational-photography'}
#- {number: 'CSED703I', name: 'Machine Learning for Graph Analysis(L)', url: 'machine-learning-for-graph-analysis'}
#- {number: 'CSED490F', name: 'Signal Processing(L)', url: 'signal-processing'}
- {number: 'EECE490U', name: 'Visual Intelligence', url: 'visual-intelligence'}
- {number: 'SIAX501', name: 'Sports Engineering and ICT Convergence', url: 'sports-engineering-and-ict-convergence'}

language_skills:
- {language: '🇰🇷 Korean', skill: 'Native Language'}
- {language: '🇺🇸 English', skill: 'Fluent (reading), Intermediate (listening, speaking, writing)'}

social:
- {icon: 'github', link: 'https://github.com/JaeyoonSSim'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jaeyoon-sim-86a4aa185/'}

contacts:
- {name: 'Jaeyoon Sim', title: 'Graduate Student', department: 'Graduate School of Artificial Intelligence(GSAI)', institution: 'POSTECH MIV LAB', institution_address: 'Pohang, Korea', email: 'simjy98[at]postech[dot]ac[dot]kr', building: 'Rist 4', image: 'assets/img/contact.jpeg'}
